# Generated by Django 4.1.5 on 2023-01-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_alter_phone_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='slug',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
