# Generated by Django 4.1.5 on 2023-01-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0005_remove_phone_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='slug',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
